venator/core/urls.py
# coding: utf-8
from django.conf.urls import patterns, include, url
from venator.core.views import Homepage


urlpatterns = patterns(
    'venator.core.views',
    url(r'^$', Homepage.as_view(), name='homepage'),
    url(r'^(?P<page>\w+)/$', 'pages', name='pages'),
    url(r'^demand/(?P<page>\w+)/$', 'pages')
)

venator/fasttracker/urls.py
# coding: utf-8
from django.conf.urls import patterns, url
from venator.fasttracker.views import Index, NewBug, BugDetail


urlpatterns = patterns(
    'venator.fasttracker.views',
    url(r'^$', Index.as_view(), name='index'),
    url(r'^new/$', NewBug.as_view(), name='newbug'),
    url(r'^(?P<pk>\d+)/', BugDetail.as_view(), name='bugdetail')
)

venator/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static


# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^fasttracker/',
        include('venator.fasttracker.urls', namespace='fasttracker')),
    url(r'', include('venator.core.urls', namespace='core')),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venator/fasttracker/models.py
from django.db import models
from django.core.urlresolvers import reverse as r


class Bug(models.Model):
    """
    """
    STATUS = (
        ("PE", "Pending"),
        ("WO", "Working"),
    )
    title = models.CharField(max_length=30)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    creator = models.CharField(max_length=30)
    status = models.CharField(max_length=2, choices=STATUS, default="PE")
    attachment = models.FileField(upload_to="fasttracker",
                                  null=True,
                                  blank=True)

    def get_absolute_url(self):
        return r("fasttracker:bugdetail", args=(self.id,))

venator/project/models.py
from django.db import models

# Create your models here.

venator/fasttracker/forms.py
# coding: utf-8

from django import forms
from venator.fasttracker.models import Bug


class BugForm(forms.Form):
    class Meta:
        model = Bug

venator/core/views.py
# Create your views here.

from django.views.generic import TemplateView
from django.shortcuts import render_to_response


class Homepage(TemplateView):
    template_name = "index.html"


def pages(request, page):
    return render_to_response(page + ".html")

venator/fasttracker/views.py
# coding: utf-8

from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.views.generic.detail import DetailView

from venator.fasttracker.models import Bug


class Index(ListView):
    # def get(self, request):
    #     if "order" in request.GET:
    #     return super(Index, self).get(request)

    queryset = Bug.objects.exclude(status="DE")

    model = Bug
    template_name = "fasttracker/index.html"


class NewBug(CreateView):
    model = Bug


class BugDetail(DetailView):
    model = Bug

venator/project/views.py
# Create your views here.

venator/core/templates/customer.html
{% extends 'site.html' %}
{% block body %}
<h1>Dashboard</h1>
<p>User: Guilherme</p>
<p>Customer: AC</p>
<h2>Open demands:</h2>
<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Priority</th>
      <th>Status</th>
      <th>Project</th>
      <th>Owner</th>
      <th>Created</th>
      <th>Due</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><a href="">1337</a></td>
      <td><a href="">Teste</a></td>
      <td><span class="badge">1</span></td>
      <td>Open</td>
      <td>Facebug</td>
      <td>Guilherme Vierno</td>
      <td>A month ago</td>
      <td>31/02/2013</td>
    </tr>
  </tbody>
</table>
{% endblock %}

venator/core/templates/index.html
{% extends 'site.html' %}
{% block body %}
<h1>Welcome</h1>
<ul>
  <li>test</li>
</ul>
{% endblock %}

venator/core/templates/login.html
{% extends 'site.html' %}
{% block body %}
<div class="row offset2">
  <h1>Login</h1>
</div>
<div class="row">
  <form class="form-horizontal">
    <div class="control-group">
      <label class="control-label" for="inputEmail">Email</label>
      <div class="controls">
        <input type="text" id="inputEmail" placeholder="Email">
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="inputPassword">Password</label>
      <div class="controls">
        <input type="password" id="inputPassword" placeholder="Password">
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <label class="checkbox">
          <input type="checkbox"> Remember me
        </label>
        <button type="submit" class="btn">Sign in</button>
        <a href="customer">Customer</a>
        <a href="admin">Admin</a>
      </div>
    </div>
  </form>
</div>
{% endblock %}

venator/core/templates/new.html
{% extends 'site.html' %}
{% block body %}
<h1>New ticket</h1>
<p>User: Guilherme</p>
<p>Customer: AC</p>
<form action="">
  <div class="row">
    <div class="span6">
      <label for="">Title</label>
      <input type="text" class="input-block-level">
    </div>
  </div>
  <div class="row">
    <div class="span6">
      <label for="">Priority</label>
      <select name="" id="">
        {% for i in 'asdf' %}
        <option value="">{{ i }}</option>
        {% endfor %}
      </select>
    </div>
  </div>
  <div class="row">
    <div class="span6">
      <label for="">Project</label>
      <select name="" id=""></select>
    </div>
  </div>
  <div class="row">
    <div class="span9">
      <label for="">Description</label>
      <textarea class="input-block-level" name="" id="" cols="30" rows="5"></textarea>
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <label for="">Files</label>
      <input type="file" name="" multiple id="">
    </div>
  </div>
  <div class="row">
    <div class="span6">
      <button class="btn btn-primary">Save</button>
    </div>
  </div>
</form>
{% endblock %}

venator/core/templates/site.html
<!DOCTYPE html>
<html>
<head>
  <title>Venator</title>
  <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">
</head>
<body>
  <div class="navbar navbar-inverse">
    <div class="navbar-inner">
      <div class="container">
        <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="brand" href="/">Venator</a>
        <div class="nav-collapse collapse">
          <ul class="nav">
            <li class="">
              <a href="/demand/new">New demand</a>
            </li>
            <li class="">
              <a href="">Reports</a>
            </li>
          </ul>
          <ul class="nav pull-right">
            <li class="">
              <a href="">Logout</a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="container">
    {% block body %}
    {% endblock %}
  </div>
  <div class="container">
    <div class="row">
      Copyright Venator, all rights reserved.
    </div>
  </div>
  <script src="http://code.jquery.com/jquery-latest.js"></script>
  <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"></script>
  {% block scripts %}
  {% endblock %}
</body>
</html>

venator/fasttracker/templates/fasttracker/base.html
<!DOCTYPE html>
<html>
  <head>
    <title>FastTracker</title>
    <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.1/css/bootstrap-combined.min.css" rel="stylesheet">
  </head>
  <body>
    <div class="navbar navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="brand" href="{% url 'fasttracker:index' %}">FastTracker</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="">
                <a href="{% url 'fasttracker:newbug' %}">New bug</a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="container">
      {% block body %}
      {% endblock %}
    </div>
    <div class="container">
      <div class="row">
        Copyright Venator, all rights reserved.
      </div>
    </div>
    <script src="http://code.jquery.com/jquery-latest.js"></script>
    <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.2.2/js/bootstrap.min.js"></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>

venator/fasttracker/templates/fasttracker/bug_detail.html
{% extends 'fasttracker/base.html' %}

{% block body %}
<div class="row">
  <h2>{{ object.title }}</h2>
  <p>Status: {{ object.get_status_display }}</p>
  <p>Creator: {{ object.creator }}</p>
  <p>Created at: {{ object.created_at }}</p>
  <h3>Description:</h3>
  {{ object.description|linebreaks }}
  {% if object.attachment %}
  <h3>Attachment:</h3>
  <a href="{{ object.attachment.url }}">{{ object.attachment }}</a>
  {% endif %}
</div>
{% endblock %}

venator/fasttracker/templates/fasttracker/bug_form.html
{% extends 'fasttracker/base.html' %}

{% block body %}
  <div class="row">
    <form action="" method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      {{ form }}
      <div class="clear-fix"></div>
      <button class="btn btn-primary" type="submit">Enviar</button>
    </form>
  </div>
{% endblock %}

venator/fasttracker/templates/fasttracker/index.html
{% extends 'fasttracker/base.html' %}

{% block body %}
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th>ID</th>
          <th>Title</th>
          <th>Status</th>
          <th>Creator</th>
          <th>Created</th>
        </tr>
      </thead>
      <tbody>
        {% for bug in object_list %}
        <tr>
          <td>{{ bug.id }}</td>
          <td><a href="{{ bug.get_absolute_url }}">{{ bug.title }}</a></td>
          <td><span class="badge {{ bug.status }}">{{ bug.status }}</span></td>
          <td>{{ bug.creator }}</td>
          <td>{{ bug.created_at }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}